version: "3.8"
services:
  api:
    container_name: lanchonete-api
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - db
    environment:
      - PORT=8000
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: strong-password
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  mynetwork:
    driver: bridge